require "ptak.options"
require "ptak.keymaps"
require "ptak.plugins"
require "ptak.colorscheme"
require "ptak.lualine"
require "ptak.lsp-zero"
require "ptak.illuminate"
require "ptak.treesitter"
require "ptak.treesitter-context"
require "ptak.autopairs"
require "ptak.comments"
require "ptak.web-devicons"
require "ptak.neoclip"
require "ptak.telescope"
require "ptak.gitsigns"
require "ptak.nvim-tree"
require "ptak.undotree"
--[[ require "ptak.indent_blankline" ]]
